apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: three-tier
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31548
