apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: three-tier
spec:
  selector:
    app: backend
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 31820
